# Generated by Django 3.2.15 on 2022-08-24 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20220824_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('name', models.CharField(max_length=15, verbose_name='食事の種類')),
            ],
        ),
        migrations.AddField(
            model_name='foodmemory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.foodcategory', verbose_name='カテゴリ'),
        ),
    ]
