# Generated by Django 4.1.2 on 2022-10-26 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0007_trophy_today_time_trophy_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
        migrations.AddField(
            model_name='foodmemory',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='自由記入欄'),
        ),
        migrations.AlterField(
            model_name='foodmemory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='fitness/food/', verbose_name='食事画像'),
        ),
    ]
