# Generated by Django 4.1.2 on 2022-10-26 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_foodcategory_user_foodmemory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessmemory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fitness.fitnesscategory', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='foodmemory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitness.foodcategory', verbose_name='カテゴリ'),
        ),
    ]
