# Generated by Django 4.1.3 on 2022-11-09 09:47

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0009_alter_fitnessmemory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessmemory',
            name='time',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=1))], verbose_name='運動時間'),
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('title', models.CharField(max_length=30, verbose_name='目標')),
                ('done', models.BooleanField(default=False, verbose_name='達成済み')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('weight', models.IntegerField(verbose_name='体重(kg)')),
                ('height', models.IntegerField(verbose_name='身長(cm)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
            ],
        ),
    ]
