# Generated by Django 4.1.2 on 2022-11-15 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_alter_fitnessmemory_time_target_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 15), verbose_name='記録日'),
            preserve_default=False,
        ),
    ]
